### ISSUE TITLE
Npm version

### ISSUE THREAD

**Issue by nafizb** [Kaelinator/quora-scraper#5]
Can you update npm version(sync with github)?

**Comment by Kaelinator** [comment]
Do you mind clarifying? I've now synced my local changes.

**Comment by Kaelinator** [comment]
Oh! I assume you mean fixing the lodash dependency vulnerability. I'm on it!

**Comment by Kaelinator** [comment]
Let me know if that's good!

**Comment by nafizb** [comment]
I mean https://www.npmjs.com/package/quora-scraper  :D
